In [5]:
import pandas as pd
import numpy as np

In [6]:
data=pd.read_csv(r'C:\Users\USER\Desktop\coding\Project\show suggestion system/netflix_titles.csv')
data

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
0,s1,Movie,Dick Johnson Is Dead,Kirsten Johnson,NaN,United States,"September 25, 2021",2020,PG-13,90 min,Documentaries,"As her father nears the end of his life, filmm..."
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
...,...,...,...,...,...,...,...,...,...,...,...,...
8802,s8803,Movie,Zodiac,David Fincher,"Mark Ruffalo, Jake Gyllenhaal, Robert Downey J...",United States,"November 20, 2019",2007,R,158 min,"Cult Movies, Dramas, Thrillers","A political cartoonist, a crime reporter and a..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."
8804,s8805,Movie,Zombieland,Ruben Fleischer,"Jesse Eisenberg, Woody Harrelson, Emma Stone, ...",United States,"November 1, 2019",2009,R,88 min,"Comedies, Horror Movies",Looking to survive in a world taken over by zo...
8805,s8806,Movie,Zoom,Peter Hewitt,"Tim Allen, Courteney Cox, Chevy Chase, Kate Ma...",United States,"January 11, 2020",2006,PG,88 min,"Children & Family Movies, Comedies","Dragged from civilian life, a former superhero..."
8806,s8807,Movie,Zubaan,Mozez Singh,"Vicky Kaushal, Sarah-Jane Dias, Raaghav Chanan...",India,"March 2, 2019",2015,TV-14,111 min,"Dramas, International Movies, Music & Musicals",A scrappy but poor boy worms his way into a ty...

In [7]:
shows=data[data['type']=='TV Show']
shows

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
1,s2,TV Show,Blood & Water,NaN,"Ama Qamata, Khosi Ngema, Gail Mabalane, Thaban...",South Africa,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, TV Dramas, TV Mysteries","After crossing paths at a party, a Cape Town t..."
2,s3,TV Show,Ganglands,Julien Leclercq,"Sami Bouajila, Tracy Gotoas, Samuel Jouy, Nabi...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Act...",To protect his family from a powerful drug lor...
3,s4,TV Show,Jailbirds New Orleans,NaN,NaN,NaN,"September 24, 2021",2021,TV-MA,1 Season,"Docuseries, Reality TV","Feuds, flirtations and toilet talk go down amo..."
4,s5,TV Show,Kota Factory,NaN,"Mayur More, Jitendra Kumar, Ranjan Raj, Alam K...",India,"September 24, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, TV ...",In a city of coaching centers known to train I...
5,s6,TV Show,Midnight Mass,Mike Flanagan,"Kate Siegel, Zach Gilford, Hamish Linklater, H...",NaN,"September 24, 2021",2021,TV-MA,1 Season,"TV Dramas, TV Horror, TV Mysteries",The arrival of a charismatic young priest brin...
...,...,...,...,...,...,...,...,...,...,...,...,...
8795,s8796,TV Show,Yu-Gi-Oh! Arc-V,NaN,"Mike Liscio, Emily Bauer, Billy Bob Thompson, ...","Japan, Canada","May 1, 2018",2015,TV-Y7,2 Seasons,"Anime Series, Kids' TV",Now that he's discovered the Pendulum Summonin...
8796,s8797,TV Show,Yunus Emre,NaN,"GÃ¶khan Atalay, Payidar TÃ¼fekÃ§ioglu, Baran Akbu...",Turkey,"January 17, 2017",2016,TV-PG,2 Seasons,"International TV Shows, TV Dramas","During the Mongol invasions, Yunus Emre leaves..."
8797,s8798,TV Show,Zak Storm,NaN,"Michael Johnston, Jessica Gee-George, Christin...","United States, France, South Korea, Indonesia","September 13, 2018",2016,TV-Y7,3 Seasons,Kids' TV,Teen surfer Zak Storm is mysteriously transpor...
8800,s8801,TV Show,Zindagi Gulzar Hai,NaN,"Sanam Saeed, Fawad Khan, Ayesha Omer, Mehreen ...",Pakistan,"December 15, 2016",2012,TV-PG,1 Season,"International TV Shows, Romantic TV Shows, TV ...","Strong-willed, middle-class Kashaf and carefre..."
8803,s8804,TV Show,Zombie Dumb,NaN,NaN,NaN,"July 1, 2019",2018,TV-Y7,2 Seasons,"Kids' TV, Korean TV Shows, TV Comedies","While living alone in a spooky town, a young g..."

In [8]:
shows.dropna(inplace=True)
shows.shape

C:\Users\USER\AppData\Local\Temp\ipykernel_21500\3658345333.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shows.dropna(inplace=True)

(147, 12)

In [9]:
shows[shows['director'].notna()]

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,Andy Devonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
198,s199,TV Show,King of Boys: The Return of the King,Kemi Adetiba,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,"August 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...
273,s274,TV Show,Gone for Good,Juan Carlos Medina,"Finnegan Oldfield, Nicolas Duvauchelle, Guilla...",France,"August 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","Ten years after losing two loved ones, a man i..."
276,s277,TV Show,Valeria,Inma Torrente,"Diana GÃ³mez, Silma LÃ³pez, Paula Malia, Teresa ...",Spain,"August 13, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, Spa...",A writer in creative and marital crises finds ...
297,s298,TV Show,Navarasa,"Bejoy Nambiar, Priyadarshan, Karthik Narain, V...","Suriya, Vijay Sethupathi, Revathy, Prakash Raj...",India,"August 6, 2021",2021,TV-MA,1 Season,TV Shows,"From amusement to awe, the nine human emotions..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8172,s8173,TV Show,Th Eena Meena Deeka Chase Comedy Show,Dheeraj Berry,"Sanjay Keni, Priya Raina",India,"March 31, 2018",2015,TV-Y7,1 Season,"Kids' TV, TV Comedies","A hungry fox and three resourceful, surprising..."
8214,s8215,TV Show,The Blue Planet: A Natural History of the Oceans,Alastair Fothergill,David Attenborough,United Kingdom,"October 10, 2015",2001,TV-G,1 Season,"British TV Shows, Docuseries, International TV...",David Attenborough narrates this definitive ex...
8293,s8294,TV Show,The Fear,Michael Samuels,"Peter Mullan, Anastasia Hille, Harry Lloyd, Pa...",United Kingdom,"March 31, 2017",2012,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Richie Beckett is an aging Brighton crime boss...
8302,s8303,TV Show,The Five,Mark Tonderai,"Tom Cullen, O.T. Fagbenle, Lee Ingleby, Sarah ...",United Kingdom,"September 15, 2017",2016,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Twenty years after 5-year-old Jesse disappears...
8599,s8600,TV Show,Toast of London,Michael Cumming,"Matt Berry, Robert Bathurst, Doon Mackichan, S...",United Kingdom,"September 1, 2017",2015,TV-MA,3 Seasons,"British TV Shows, Classic & Cult TV, TV Comedies","After a divorce and fatal career move, a class..."

In [10]:
# One-liner without apply:
director_list = shows['director'].str.replace(' ', '').tolist()
director_list
shows['director']=director_list
shows

C:\Users\USER\AppData\Local\Temp\ipykernel_21500\568651191.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shows['director']=director_list

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,AndyDevonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",United Kingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
198,s199,TV Show,King of Boys: The Return of the King,KemiAdetiba,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,"August 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...
273,s274,TV Show,Gone for Good,JuanCarlosMedina,"Finnegan Oldfield, Nicolas Duvauchelle, Guilla...",France,"August 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","Ten years after losing two loved ones, a man i..."
276,s277,TV Show,Valeria,InmaTorrente,"Diana GÃ³mez, Silma LÃ³pez, Paula Malia, Teresa ...",Spain,"August 13, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, Spa...",A writer in creative and marital crises finds ...
297,s298,TV Show,Navarasa,"BejoyNambiar,Priyadarshan,KarthikNarain,Vasant...","Suriya, Vijay Sethupathi, Revathy, Prakash Raj...",India,"August 6, 2021",2021,TV-MA,1 Season,TV Shows,"From amusement to awe, the nine human emotions..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8172,s8173,TV Show,Th Eena Meena Deeka Chase Comedy Show,DheerajBerry,"Sanjay Keni, Priya Raina",India,"March 31, 2018",2015,TV-Y7,1 Season,"Kids' TV, TV Comedies","A hungry fox and three resourceful, surprising..."
8214,s8215,TV Show,The Blue Planet: A Natural History of the Oceans,AlastairFothergill,David Attenborough,United Kingdom,"October 10, 2015",2001,TV-G,1 Season,"British TV Shows, Docuseries, International TV...",David Attenborough narrates this definitive ex...
8293,s8294,TV Show,The Fear,MichaelSamuels,"Peter Mullan, Anastasia Hille, Harry Lloyd, Pa...",United Kingdom,"March 31, 2017",2012,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Richie Beckett is an aging Brighton crime boss...
8302,s8303,TV Show,The Five,MarkTonderai,"Tom Cullen, O.T. Fagbenle, Lee Ingleby, Sarah ...",United Kingdom,"September 15, 2017",2016,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Twenty years after 5-year-old Jesse disappears...
8599,s8600,TV Show,Toast of London,MichaelCumming,"Matt Berry, Robert Bathurst, Doon Mackichan, S...",United Kingdom,"September 1, 2017",2015,TV-MA,3 Seasons,"British TV Shows, Classic & Cult TV, TV Comedies","After a divorce and fatal career move, a class..."

In [11]:
shows['country']=shows['country'].str.replace(' ', '').tolist()
shows

C:\Users\USER\AppData\Local\Temp\ipykernel_21500\828824865.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shows['country']=shows['country'].str.replace(' ', '').tolist()

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
8,s9,TV Show,The Great British Baking Show,AndyDevonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",UnitedKingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...
198,s199,TV Show,King of Boys: The Return of the King,KemiAdetiba,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,"August 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...
273,s274,TV Show,Gone for Good,JuanCarlosMedina,"Finnegan Oldfield, Nicolas Duvauchelle, Guilla...",France,"August 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","Ten years after losing two loved ones, a man i..."
276,s277,TV Show,Valeria,InmaTorrente,"Diana GÃ³mez, Silma LÃ³pez, Paula Malia, Teresa ...",Spain,"August 13, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, Spa...",A writer in creative and marital crises finds ...
297,s298,TV Show,Navarasa,"BejoyNambiar,Priyadarshan,KarthikNarain,Vasant...","Suriya, Vijay Sethupathi, Revathy, Prakash Raj...",India,"August 6, 2021",2021,TV-MA,1 Season,TV Shows,"From amusement to awe, the nine human emotions..."
...,...,...,...,...,...,...,...,...,...,...,...,...
8172,s8173,TV Show,Th Eena Meena Deeka Chase Comedy Show,DheerajBerry,"Sanjay Keni, Priya Raina",India,"March 31, 2018",2015,TV-Y7,1 Season,"Kids' TV, TV Comedies","A hungry fox and three resourceful, surprising..."
8214,s8215,TV Show,The Blue Planet: A Natural History of the Oceans,AlastairFothergill,David Attenborough,UnitedKingdom,"October 10, 2015",2001,TV-G,1 Season,"British TV Shows, Docuseries, International TV...",David Attenborough narrates this definitive ex...
8293,s8294,TV Show,The Fear,MichaelSamuels,"Peter Mullan, Anastasia Hille, Harry Lloyd, Pa...",UnitedKingdom,"March 31, 2017",2012,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Richie Beckett is an aging Brighton crime boss...
8302,s8303,TV Show,The Five,MarkTonderai,"Tom Cullen, O.T. Fagbenle, Lee Ingleby, Sarah ...",UnitedKingdom,"September 15, 2017",2016,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Twenty years after 5-year-old Jesse disappears...
8599,s8600,TV Show,Toast of London,MichaelCumming,"Matt Berry, Robert Bathurst, Doon Mackichan, S...",UnitedKingdom,"September 1, 2017",2015,TV-MA,3 Seasons,"British TV Shows, Classic & Cult TV, TV Comedies","After a divorce and fatal career move, a class..."

In [12]:
def convert3(text):
    L = []
    # Check if input is already a list
    if isinstance(text, list):
        names = text
    else:
        # If it's a string, split it
        names = text.split(',')
    
    counter = 0
    for name in names:
        if counter < 3:
            # Remove spaces within each name but keep the commas
            no_space_name = name.strip()
            L.append(no_space_name)
        counter += 1
    return ','.join(L)  # Join with commas

# Apply the function
shows['top3_cast'] = shows['cast'].apply(convert3)
shows

C:\Users\USER\AppData\Local\Temp\ipykernel_21500\2311106575.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shows['top3_cast'] = shows['cast'].apply(convert3)

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description,top3_cast
8,s9,TV Show,The Great British Baking Show,AndyDevonshire,"Mel Giedroyc, Sue Perkins, Mary Berry, Paul Ho...",UnitedKingdom,"September 24, 2021",2021,TV-14,9 Seasons,"British TV Shows, Reality TV",A talented batch of amateur bakers face off in...,"Mel Giedroyc,Sue Perkins,Mary Berry"
198,s199,TV Show,King of Boys: The Return of the King,KemiAdetiba,"Sola Sobowale, Toni Tones, Richard Mofe-Damijo...",Nigeria,"August 27, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas",Alhaja Eniola Salami starts anew and sets her ...,"Sola Sobowale,Toni Tones,Richard Mofe-Damijo"
273,s274,TV Show,Gone for Good,JuanCarlosMedina,"Finnegan Oldfield, Nicolas Duvauchelle, Guilla...",France,"August 13, 2021",2021,TV-MA,1 Season,"Crime TV Shows, International TV Shows, TV Dramas","Ten years after losing two loved ones, a man i...","Finnegan Oldfield,Nicolas Duvauchelle,Guillaum..."
276,s277,TV Show,Valeria,InmaTorrente,"Diana GÃ³mez, Silma LÃ³pez, Paula Malia, Teresa ...",Spain,"August 13, 2021",2021,TV-MA,2 Seasons,"International TV Shows, Romantic TV Shows, Spa...",A writer in creative and marital crises finds ...,"Diana GÃ³mez,Silma LÃ³pez,Paula Malia"
297,s298,TV Show,Navarasa,"BejoyNambiar,Priyadarshan,KarthikNarain,Vasant...","Suriya, Vijay Sethupathi, Revathy, Prakash Raj...",India,"August 6, 2021",2021,TV-MA,1 Season,TV Shows,"From amusement to awe, the nine human emotions...","Suriya,Vijay Sethupathi,Revathy"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
8172,s8173,TV Show,Th Eena Meena Deeka Chase Comedy Show,DheerajBerry,"Sanjay Keni, Priya Raina",India,"March 31, 2018",2015,TV-Y7,1 Season,"Kids' TV, TV Comedies","A hungry fox and three resourceful, surprising...","Sanjay Keni,Priya Raina"
8214,s8215,TV Show,The Blue Planet: A Natural History of the Oceans,AlastairFothergill,David Attenborough,UnitedKingdom,"October 10, 2015",2001,TV-G,1 Season,"British TV Shows, Docuseries, International TV...",David Attenborough narrates this definitive ex...,David Attenborough
8293,s8294,TV Show,The Fear,MichaelSamuels,"Peter Mullan, Anastasia Hille, Harry Lloyd, Pa...",UnitedKingdom,"March 31, 2017",2012,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Richie Beckett is an aging Brighton crime boss...,"Peter Mullan,Anastasia Hille,Harry Lloyd"
8302,s8303,TV Show,The Five,MarkTonderai,"Tom Cullen, O.T. Fagbenle, Lee Ingleby, Sarah ...",UnitedKingdom,"September 15, 2017",2016,TV-MA,1 Season,"British TV Shows, Crime TV Shows, TV Dramas",Twenty years after 5-year-old Jesse disappears...,"Tom Cullen,O.T. Fagbenle,Lee Ingleby"
8599,s8600,TV Show,Toast of London,MichaelCumming,"Matt Berry, Robert Bathurst, Doon Mackichan, S...",UnitedKingdom,"September 1, 2017",2015,TV-MA,3 Seasons,"British TV Shows, Classic & Cult TV, TV Comedies","After a divorce and fatal career move, a class...","Matt Berry,Robert Bathurst,Doon Mackichan"

In [13]:
def convert3(text):
    L = []
    # Check if input is already a list
    if isinstance(text, list):
        names = text
    else:
        # If it's a string, split it
        names = text.split(',')
    
    counter = 0
    for name in names:
        if counter < 3:
            # Remove all spaces within each name
            no_space_name = ''.join(name.strip().split())
            L.append(no_space_name)
        counter += 1
    return ','.join(L)  # Join with commas

# Apply the function
shows['cast'] = shows['cast'].apply(convert3)
shows
shows['tags']=shows['description']+shows['cast']+shows['country']+shows['director']+shows['listed_in']
new = shows.drop(columns=['description','cast','country','director','date_added','release_year','rating','duration','top3_cast','type','listed_in'])
new

C:\Users\USER\AppData\Local\Temp\ipykernel_21500\242999317.py:20: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shows['cast'] = shows['cast'].apply(convert3)
C:\Users\USER\AppData\Local\Temp\ipykernel_21500\242999317.py:22: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  shows['tags']=shows['description']+shows['cast']+shows['country']+shows['director']+shows['listed_in']

,show_id,title,tags
8,s9,The Great British Baking Show,A talented batch of amateur bakers face off in...
198,s199,King of Boys: The Return of the King,Alhaja Eniola Salami starts anew and sets her ...
273,s274,Gone for Good,"Ten years after losing two loved ones, a man i..."
276,s277,Valeria,A writer in creative and marital crises finds ...
297,s298,Navarasa,"From amusement to awe, the nine human emotions..."
...,...,...,...
8172,s8173,Th Eena Meena Deeka Chase Comedy Show,"A hungry fox and three resourceful, surprising..."
8214,s8215,The Blue Planet: A Natural History of the Oceans,David Attenborough narrates this definitive ex...
8293,s8294,The Fear,Richie Beckett is an aging Brighton crime boss...
8302,s8303,The Five,Twenty years after 5-year-old Jesse disappears...
8599,s8600,Toast of London,"After a divorce and fatal career move, a class..."

In [14]:
new['tags'] = new['tags']
new

,show_id,title,tags
8,s9,The Great British Baking Show,A talented batch of amateur bakers face off in...
198,s199,King of Boys: The Return of the King,Alhaja Eniola Salami starts anew and sets her ...
273,s274,Gone for Good,"Ten years after losing two loved ones, a man i..."
276,s277,Valeria,A writer in creative and marital crises finds ...
297,s298,Navarasa,"From amusement to awe, the nine human emotions..."
...,...,...,...
8172,s8173,Th Eena Meena Deeka Chase Comedy Show,"A hungry fox and three resourceful, surprising..."
8214,s8215,The Blue Planet: A Natural History of the Oceans,David Attenborough narrates this definitive ex...
8293,s8294,The Fear,Richie Beckett is an aging Brighton crime boss...
8302,s8303,The Five,Twenty years after 5-year-old Jesse disappears...
8599,s8600,Toast of London,"After a divorce and fatal career move, a class..."

In [15]:
#from sklearn.feature_extraction.text import CountVectorizer
#cv = CountVectorizer(max_features=5000,stop_words='english')

In [16]:
#vector = cv.fit_transform(new['tags']).toarray()

In [17]:
#from sklearn.metrics.pairwise import cosine_similarity

In [18]:
#similarity = cosine_similarity(vector)
#similarity

In [19]:
'''def recommend(show):
    # Get the index of the show
    show_index = new[new['title'] == show].index
    if len(show_index) == 0:
        print(f"Show '{show}' not found")
        return
    
    # Get the index relative to the current DataFrame
    relative_index = new.index.get_loc(show_index[0])
    
    # Get distances
    distances = sorted(list(enumerate(similarity[relative_index])), reverse=True, key=lambda x: x[1])
    
    print(f"\nTop 5 recommendations for '{show}':")
    for i in distances[1:6]:
        print(f"- {new.iloc[i[0]].title}")

# Usage:
'''

'def recommend(show):\n    # Get the index of the show\n    show_index = new[new[\'title\'] == show].index\n    if len(show_index) == 0:\n        print(f"Show \'{show}\' not found")\n        return\n    \n    # Get the index relative to the current DataFrame\n    relative_index = new.index.get_loc(show_index[0])\n    \n    # Get distances\n    distances = sorted(list(enumerate(similarity[relative_index])), reverse=True, key=lambda x: x[1])\n    \n    print(f"\nTop 5 recommendations for \'{show}\':")\n    for i in distances[1:6]:\n        print(f"- {new.iloc[i[0]].title}")\n\n# Usage:\n'

In [26]:
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Create TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')

# Create vectors using your DataFrame directly
vector = tfidf.fit_transform(new['tags'])
similarity = cosine_similarity(vector)

def recommend(show):
    # First let's print the available titles containing our search term
    try:
        # Find the position in our current DataFrame
        show_position = new.reset_index()
        show_position = show_position[show_position['title'] == show].index[0]
        
        # Get distances
        distances = sorted(list(enumerate(similarity[show_position])), reverse=True, key=lambda x: x[1])
        
        print(f"\nTop 5 recommendations for '{show}':")
        for i in distances[1:6]:
            print(f"- {new.iloc[i[0]]['title']}")
            
    except IndexError:
        print(f"Show '{show}' not found")

# Test it
recommend('Valeria')

Searching for 'Valeria'...

Top 5 recommendations for 'Valeria':
- Velvet
- You
- BolÃ­var
- Camelia la Texana
- Hook

In [98]:
#recommend('Valeria')

Top 5 recommendations for 'Valeria':
- Velvet
- BolÃ­var
- Camelia la Texana
- Someone Has to Die
- Crime Diaries: Night Out